server:
  host: 0.0.0.0
  port: 8080
database:
  host: account-db
  port: 5432
  user: root
  password: password
  name: account
  sslmode: disable
defaultaccountname: "savings account"
transactiontypenormal: 0
