version: "3.8"

services:
  user:
    image: bachelor/user
    restart: unless-stopped
    build:
      context: ${docker_compose_path_offset_to_root}
      dockerfile: /cmd/user/Dockerfile
      args:
        - GO_VERSION=${go_version}
        - service_path=cmd/user
    #ports:
    #  - "8080:8080"
    depends_on:
      - user-db

  user-db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${user_db_user}
      POSTGRES_PASSWORD: ${user_db_password}
      POSTGRES_DB: ${user_db_name}
    #ports:
    #  - "5432:5432"
    volumes:
      - user_db_data:/var/lib/mysql

  account:
    image: bachelor/account
    restart: unless-stopped
    build:
      context: ${docker_compose_path_offset_to_root}
      dockerfile: /cmd/account/Dockerfile
      args:
        - GO_VERSION=${go_version}
        - service_path=cmd/account
    #ports:
    #  - "8080:8080"
    depends_on:
      - account-db

  account-db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${account_db_user}
      POSTGRES_PASSWORD: ${account_db_password}
      POSTGRES_DB: ${account_db_name}
    #ports:
    #  - "5432:5432"
    volumes:
      - account_db_data:/var/lib/mysql

  transaction-history:
    image: bachelor/transaction-history
    restart: unless-stopped
    build:
      context: ${docker_compose_path_offset_to_root}
      dockerfile: /cmd/transaction-history/Dockerfile
      args:
        - GO_VERSION=${go_version}
        - service_path=cmd/transaction-history
    #ports:
    #  - "8080:8080"
    depends_on:
      - transaction-history-db

  transaction-history-db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${transaction_history_db_user}
      POSTGRES_PASSWORD: ${transaction_history_db_password}
      POSTGRES_DB: ${transaction_history_db_name}
    #ports:
    #  - "5432:5432"
    volumes:
      - transaction_history_db_data:/var/lib/mysql

  transaction:
    image: bachelor/transaction
    restart: unless-stopped
    build:
      context: ${docker_compose_path_offset_to_root}
      dockerfile: /cmd/transaction/Dockerfile
      args:
        - GO_VERSION=${go_version}
        - service_path=cmd/transaction
    #ports:
    #  - "8080:8080"
    depends_on:
      - transaction-queue

  transaction-queue:
    image: rabbitmq:3.11.13-management
    restart: unless-stopped
    #ports:
    #  - "5672:5672"
    #  - "15672:15672"
    volumes:
      - transaction_queue_data:/var/lib/rabbitmq

  transaction-orchestrator:
    image: bachelor/transaction-orchestrator
    restart: unless-stopped
    build:
      context: ${docker_compose_path_offset_to_root}
      dockerfile: /cmd/transaction-orchestrator/Dockerfile
      args:
        - GO_VERSION=${go_version}
        - service_path=cmd/transaction-orchestrator
    #ports:
    #  - "8080:8080"
    depends_on:
      - transaction-queue

  transaction-orchestrator-cache:
    image: redis:7.0.10
    restart: unless-stopped
    #ports:
    #  - "6379:6379"

  gateway:
    image: nginx:1.23.4
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${docker_compose_path_offset_to_root}/cmd/gateway/nginx.conf:/etc/nginx/nginx.conf
      - ${docker_compose_path_offset_to_root}/cmd/gateway/html/:/usr/share/nginx/html/
    depends_on:
      - user
      - account
      - transaction-history
      - transaction
    #  - failure-finder-manager
    #  - frontend

volumes:
  user_db_data:
  account_db_data:
  transaction_history_db_data:
  transaction_queue_data:
