# Continuous Integration workflow for GitHub Actions
name: continuous-integration

# When to run the workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Jobs to run
jobs:
  # Build services with Docker
  build-docker-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the services
        services:
          - user
          - account
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: docker-compose/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # (Sign in to Docker Hub here)

      # (Add push to docker hub here)
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./cmd/${{ matrix.service }}
          file: ./cmd/${{ matrix.service }}/Dockerfile
          push: false
          load: true
          tags: local/${{ matrix.service }}:latest
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            service_path=cmd/${{ matrix.service }}
